package com.smart_tiger.monio.modules.calendarrecurrencerules;

import jakarta.persistence.*;
import lombok.*;
import org.joda.time.LocalDateTime;

import java.io.Serial;
import java.io.Serializable;
import java.util.Objects;
import java.util.UUID;

/**
 * Represents a recurrence rule entity stored in the database. This entity defines the
 * rules for recurring events, including start date, end date, interval, and frequency.
 * It maps to the "recurrence_rules" table in the "ledger" schema.
 *
 *
 * Fields:
 * - id: Unique identifier for the recurrence rule.
 * - startDate: The start date of the recurring event. Cannot be null.
 * - endDate: The end date of the recurring event. Cannot be null.
 * - ruleName: The name or label of the recurrence rule. Cannot be null and restricted to 100 characters.
 * - interval: The interval at which the recurrence occurs. Cannot be null.
 * - frequency: The type of recurrence frequency (e.g., daily, weekly, monthly). Cannot be null and stored as a string.
 *
 *
 * Equality and Hashing:
 * Equality and hash code are based on the unique identifier (id). These methods take into account
 * proxy instances generated by Hibernate to ensure proper functioning within ORM contexts.
 */
@Entity
@Table(name = "recurrence_rules", schema = "ledger")
@Getter
@Setter
@ToString
@RequiredArgsConstructor
public class RecurrenceRule implements Serializable {

    @Serial
    private static final long serialVersionUID = -3285659731333633741L;

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    @Column(name = "start_date", nullable = false)
    private LocalDateTime startDate;

    @Column(name = "end_date", nullable = false)
    private LocalDateTime endDate;

    @Column(name = "rule_name", nullable = false, length = 100)
    private String ruleName;

    @Column(name = "interval", nullable = false)
    private int interval;

    @Enumerated(EnumType.STRING)
    @Column(name = "frequency", nullable = false, length = 255)
    private RecurrenceFrequency frequency;

    @Override
    public final boolean equals(Object o) {
        if (this == o) return true;
        if (o == null) return false;
        if (!(o instanceof RecurrenceRule that)) return false;
        return getId() != null && Objects.equals(getId(), that.getId());
    }

    @Override
    public final int hashCode() {
        return getId() != null ? getId().hashCode() : 31;
    }

}
